<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.github.lijolo</groupId>
  <artifactId>lijolo</artifactId>
  <version>HEAD-SNAPSHOT</version>
  <packaging>pom</packaging>

  <description>lijolo model</description>

  <inceptionYear>2025</inceptionYear>

  <scm>
    <connection>scm:git@github.com:FrankHossfeld/lijolo-model.git</connection>
    <developerConnection>scm:git:git@github.com:FrankHossfeld/lijolo-model.git</developerConnection>
    <url>scm:git:https://github.com/FrankHossfeld/lijolo-model</url>
  </scm>

  <issueManagement>
    <system>GitHub</system>
    <url>https://github.com/FrankHossfeld/lijolo-model/issues</url>
  </issueManagement>

  <properties>
    <aws.version>2.38.7</aws.version>
    <jooq.version>3.20.8</jooq.version>
    <liquibase.version>5.0.1</liquibase.version>
    <postgresql.driver.version>42.7.8</postgresql.driver.version>

    <testcontainers.version>1.21.1</testcontainers.version>

    <plugin.version.compiler>3.12.1</plugin.version.compiler>

    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>software.amazon.awssdk</groupId>
        <artifactId>bom</artifactId>
        <version>${aws.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.testcontainers</groupId>
        <artifactId>testcontainers-bom</artifactId>
        <version>${testcontainers.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <dependency>
        <groupId>org.liquibase</groupId>
        <artifactId>liquibase-core</artifactId>
        <version>${liquibase.version}</version>
      </dependency>

      <dependency>
        <groupId>org.jooq</groupId>
        <artifactId>jooq</artifactId>
        <version>${jooq.version}</version>
      </dependency>
      <dependency>
        <groupId>org.jooq</groupId>
        <artifactId>jooq-meta</artifactId>
        <version>${jooq.version}</version>
      </dependency>
      <dependency>
        <groupId>org.jooq</groupId>
        <artifactId>jooq-codegen</artifactId>
        <version>${jooq.version}</version>
      </dependency>

      <dependency>
        <groupId>org.postgresql</groupId>
        <artifactId>postgresql</artifactId>
        <version>${postgresql.driver.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>


  </dependencies>


  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${plugin.version.compiler}</version>
          <configuration>
            <source>${maven.compiler.source}</source>
            <target>${maven.compiler.target}</target>
            <showWarnings>true</showWarnings>
            <showDeprecation>true</showDeprecation>
            <encoding>${project.build.sourceEncoding}</encoding>
            <compilerArgs>
              <compilerArgument>-Xlint:all</compilerArgument>
            </compilerArgs>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>


  <modules>
    <module>lijolo-model</module>
  </modules>
</project>