<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.github.lijolo</groupId>
    <artifactId>lijolo</artifactId>
    <version>HEAD-SNAPSHOT</version>
  </parent>

  <artifactId>lijolo-service</artifactId>
  <version>HEAD-SNAPSHOT</version>
  <packaging>jar</packaging>

  <description>lijolo service</description>

  <inceptionYear>2025</inceptionYear>

    <properties>
      <lijolo.model.version>HEAD-SNAPSHOT</lijolo.model.version>
<!--    <apache.poi.version>5.4.1</apache.poi.version>-->
<!--    <aws.version>2.31.63</aws.version>-->
<!--    <bouncycastle.bcpkix.version>1.81</bouncycastle.bcpkix.version>-->
<!--    <bouncycastle.bcprov.version>1.81</bouncycastle.bcprov.version>-->
<!--    <commens.http>4.5.14</commens.http>-->
<!--    <commens.io>2.19.0</commens.io>-->
<!--    <commens.lang3>3.18.0</commens.lang3>-->
<!--    <dom4j.version>2.1.4</dom4j.version>-->
<!--    <eis3.version>3.4.0</eis3.version>-->
<!--    <gson.version>2.13.1</gson.version>-->
<!--    <iban4g.version>2.3.0</iban4g.version>-->
<!--    <jakarta.mail.version>2.0.1</jakarta.mail.version>-->
    <jakarta.xml.binding.version>4.0.2</jakarta.xml.binding.version>
<!--    <makani-shared-model.version>HEAD-SNAPSHOT</makani-shared-model.version>-->
<!--    <makani-erechnung.version>HEAD-SNAPSHOT</makani-erechnung.version>-->
<!--    <openPdf.version>2.0.5</openPdf.version>-->
<!--    <slf4j.version>2.0.16</slf4j.version>-->
<!--    <snakeyaml.version>2.4</snakeyaml.version>-->

    <junit.platform.version>1.13.1</junit.platform.version>
    <junit.version>5.13.1</junit.version>
    <testcontainers.version>1.21.1</testcontainers.version>

<!--    <plugin.version.compiler>3.12.1</plugin.version.compiler>-->
<!--    <plugin.version.cyclonedx>2.9.1</plugin.version.cyclonedx>-->
<!--    <plugin.version.javadoc>3.11.2</plugin.version.javadoc>-->
<!--    <plugin.version.source>3.3.0</plugin.version.source>-->
<!--    <plugin.version.surefire>3.5.2</plugin.version.surefire>-->
<!--    <plugin.version.resource>3.3.1</plugin.version.resource>-->
<!--    <plugin.version.versions>2.18.0</plugin.version.versions>-->

<!--    <plugin.version.gpg>1.6</plugin.version.gpg>-->

<!--    <maven.compiler.source>21</maven.compiler.source>-->
<!--    <maven.compiler.target>21</maven.compiler.target>-->

<!--    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>-->
  </properties>

<!--  <dependencyManagement>-->
<!--    <dependencies>-->
<!--      <dependency>-->
<!--        <groupId>software.amazon.awssdk</groupId>-->
<!--        <artifactId>bom</artifactId>-->
<!--        <version>${aws.version}</version>-->
<!--        <type>pom</type>-->
<!--        <scope>import</scope>-->
<!--      </dependency>-->
<!--      <dependency>-->
<!--        <groupId>org.testcontainers</groupId>-->
<!--        <artifactId>testcontainers-bom</artifactId>-->
<!--        <version>${testcontainers.version}</version>-->
<!--        <type>pom</type>-->
<!--        <scope>import</scope>-->
<!--      </dependency>-->
<!--    </dependencies>-->
<!--  </dependencyManagement>-->

  <dependencies>
    <dependency>
      <groupId>io.github.lijolo</groupId>
      <artifactId>lijolo-model</artifactId>
      <version>${lijolo.model.version}</version>
    </dependency>
<!--    <dependency>-->
<!--      <groupId>solutions.nalu.eis</groupId>-->
<!--      <artifactId>eis3</artifactId>-->
<!--      <version>${eis3.version}</version>-->
<!--      <exclusions>-->
<!--        <exclusion>-->
<!--          <artifactId>slf4j-api</artifactId>-->
<!--          <groupId>org.slf4j</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>jackson-annotations</artifactId>-->
<!--          <groupId>com.fasterxml.jackson.core</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>reactive-streams</artifactId>-->
<!--          <groupId>org.reactivestreams</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>jakarta.xml.bind-api</artifactId>-->
<!--          <groupId>jakarta.xml.bind</groupId>-->
<!--        </exclusion>-->
<!--      </exclusions>-->
<!--    </dependency>-->

<!--    <dependency>-->
<!--      <groupId>solutions.nalu.suite.makani</groupId>-->
<!--      <artifactId>makani-erechnung-service</artifactId>-->
<!--      <version>${makani-erechnung.version}</version>-->
<!--      <exclusions>-->
<!--        <exclusion>-->
<!--          <artifactId>commons-logging</artifactId>-->
<!--          <groupId>commons-logging</groupId>-->
<!--        </exclusion>-->
<!--      </exclusions>-->
<!--    </dependency>-->

<!--    <dependency>-->
<!--      <groupId>solutions.nalu.suite.makani</groupId>-->
<!--      <artifactId>makani-shared-model</artifactId>-->
<!--      <version>${makani-shared-model.version}</version>-->
<!--      <exclusions>-->
<!--        <exclusion>-->
<!--          <artifactId>snakeyaml</artifactId>-->
<!--          <groupId>org.yaml</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>commons-logging</artifactId>-->
<!--          <groupId>commons-logging</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>commons-io</artifactId>-->
<!--          <groupId>commons-io</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>httpclient</artifactId>-->
<!--          <groupId>org.apache.httpcomponents</groupId>-->
<!--        </exclusion>-->
<!--      </exclusions>-->
<!--    </dependency>-->
    <dependency>
      <groupId>io.github.lijolo</groupId>
      <artifactId>lijolo-model</artifactId>
      <version>${lijolo.model.version}</version>
      <type>test-jar</type>
    </dependency>

<!--    <dependency>-->
<!--      <groupId>org.dom4j</groupId>-->
<!--      <artifactId>dom4j</artifactId>-->
<!--      <version>${dom4j.version}</version>-->
<!--    </dependency>-->

<!--    <dependency>-->
<!--      <groupId>com.github.librepdf</groupId>-->
<!--      <artifactId>openpdf</artifactId>-->
<!--      <version>${openPdf.version}</version>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>org.bouncycastle</groupId>-->
<!--      <artifactId>bcprov-jdk18on</artifactId>-->
<!--      <version>${bouncycastle.bcprov.version}</version>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>org.bouncycastle</groupId>-->
<!--      <artifactId>bcpkix-jdk18on</artifactId>-->
<!--      <version>${bouncycastle.bcpkix.version}</version>-->
<!--    </dependency>-->

<!--    <dependency>-->
<!--      <groupId>org.apache.poi</groupId>-->
<!--      <artifactId>poi</artifactId>-->
<!--      <version>${apache.poi.version}</version>-->
<!--      <exclusions>-->
<!--        <exclusion>-->
<!--          <artifactId>slf4j-api</artifactId>-->
<!--          <groupId>org.slf4j</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>commons-io</artifactId>-->
<!--          <groupId>commons-io</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>log4j-api</artifactId>-->
<!--          <groupId>org.apache.logging.log4j</groupId>-->
<!--        </exclusion>-->
<!--      </exclusions>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>org.apache.poi</groupId>-->
<!--      <artifactId>poi-ooxml</artifactId>-->
<!--      <version>${apache.poi.version}</version>-->
<!--      <exclusions>-->
<!--        <exclusion>-->
<!--          <artifactId>bcpkix-jdk15on</artifactId>-->
<!--          <groupId>org.bouncycastle</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>bcprov-jdk15on</artifactId>-->
<!--          <groupId>org.bouncycastle</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>slf4j-api</artifactId>-->
<!--          <groupId>org.slf4j</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>xml-apis</artifactId>-->
<!--          <groupId>xml-apis</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>jakarta.xml.bind-api</artifactId>-->
<!--          <groupId>jakarta.xml.bind</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>commons-compress</artifactId>-->
<!--          <groupId>org.apache.commons</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>commons-io</artifactId>-->
<!--          <groupId>commons-io</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>log4j-api</artifactId>-->
<!--          <groupId>org.apache.logging.log4j</groupId>-->
<!--        </exclusion>-->
<!--      </exclusions>-->
<!--    </dependency>-->

<!--    <dependency>-->
<!--      <groupId>com.google.code.gson</groupId>-->
<!--      <artifactId>gson</artifactId>-->
<!--      <version>${gson.version}</version>-->
<!--      <exclusions>-->
<!--        <exclusion>-->
<!--          <artifactId>error_prone_annotations</artifactId>-->
<!--          <groupId>com.google.errorprone</groupId>-->
<!--        </exclusion>-->
<!--      </exclusions>-->
<!--    </dependency>-->

    <dependency>
      <groupId>jakarta.xml.bind</groupId>
      <artifactId>jakarta.xml.bind-api</artifactId>
      <version>${jakarta.xml.binding.version}</version>
    </dependency>
<!--    <dependency>-->
<!--      <groupId>software.amazon.awssdk</groupId>-->
<!--      <artifactId>ec2</artifactId>-->
<!--      <exclusions>-->
<!--        <exclusion>-->
<!--          <artifactId>slf4j-api</artifactId>-->
<!--          <groupId>org.slf4j</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>commons-codec</artifactId>-->
<!--          <groupId>commons-codec</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>netty-codec-http</artifactId>-->
<!--          <groupId>io.netty</groupId>-->
<!--        </exclusion>-->
<!--        <exclusion>-->
<!--          <artifactId>netty-handler</artifactId>-->
<!--          <groupId>io.netty</groupId>-->
<!--        </exclusion>-->
<!--      </exclusions>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>software.amazon.awssdk</groupId>-->
<!--      <artifactId>s3</artifactId>-->
<!--      <exclusions>-->
<!--        <exclusion>-->
<!--          <artifactId>slf4j-api</artifactId>-->
<!--          <groupId>org.slf4j</groupId>-->
<!--        </exclusion>-->
<!--      </exclusions>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>software.amazon.awssdk</groupId>-->
<!--      <artifactId>sqs</artifactId>-->
<!--      <scope>test</scope>-->
<!--    </dependency>-->

<!--    &lt;!&ndash; https://mvnrepository.com/artifact/org.yaml/snakeyaml &ndash;&gt;-->
<!--    <dependency>-->
<!--      <groupId>org.yaml</groupId>-->
<!--      <artifactId>snakeyaml</artifactId>-->
<!--      <version>${snakeyaml.version}</version>-->
<!--    </dependency>-->

<!--    &lt;!&ndash; IBAN4G &ndash;&gt;-->
<!--    <dependency>-->
<!--      <groupId>com.github.nalukit</groupId>-->
<!--      <artifactId>iban4g</artifactId>-->
<!--      <version>${iban4g.version}</version>-->
<!--    </dependency>-->

    <!-- https://mvnrepository.com/artifact/org.slf4j/slf4j-api -->
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>

<!--    &lt;!&ndash; https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 &ndash;&gt;-->
<!--    <dependency>-->
<!--      <groupId>org.apache.commons</groupId>-->
<!--      <artifactId>commons-lang3</artifactId>-->
<!--      <version>${commens.lang3}</version>-->
<!--    </dependency>-->
<!--    &lt;!&ndash; https://mvnrepository.com/artifact/commons-io/commons-io &ndash;&gt;-->
<!--    <dependency>-->
<!--      <groupId>commons-io</groupId>-->
<!--      <artifactId>commons-io</artifactId>-->
<!--      <version>${commens.io}</version>-->
<!--    </dependency>-->

<!--    &lt;!&ndash; https://mvnrepository.com/artifact/com.sun.mail/jakarta.mail &ndash;&gt;-->
<!--    <dependency>-->
<!--      <groupId>com.sun.mail</groupId>-->
<!--      <artifactId>jakarta.mail</artifactId>-->
<!--      <version>${jakarta.mail.version}</version>-->
<!--    </dependency>-->

    <!-- test resources -->
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.junit.platform/junit-platform-suite-api -->
    <dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-suite-api</artifactId>
      <version>${junit.platform.version}</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>testcontainers</artifactId>
      <version>${testcontainers.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>postgresql</artifactId>
      <version>${testcontainers.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>localstack</artifactId>
      <version>${testcontainers.version}</version>
      <scope>test</scope>
    </dependency>
<!--    &lt;!&ndash; https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient &ndash;&gt;-->
<!--    <dependency>-->
<!--      <groupId>org.apache.httpcomponents</groupId>-->
<!--      <artifactId>httpclient</artifactId>-->
<!--      <version>${commens.http}</version>-->
<!--      <scope>test</scope>-->
<!--      <exclusions>-->
<!--        <exclusion>-->
<!--          <artifactId>commons-codec</artifactId>-->
<!--          <groupId>commons-codec</groupId>-->
<!--        </exclusion>-->
<!--      </exclusions>-->
<!--    </dependency>-->
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>${maven.compiler.source}</source>
          <target>${maven.compiler.target}</target>
          <showWarnings>true</showWarnings>
          <showDeprecation>true</showDeprecation>
          <meminitial>128m</meminitial>
          <maxmem>1024m</maxmem>
          <encoding>${project.build.sourceEncoding}</encoding>
          <compilerArgs>
            <compilerArgument>-Xlint:all</compilerArgument>
          </compilerArgs>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar-no-fork</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <configuration>
          <additionalOptions>
            <additionalOption>-Xdoclint:none</additionalOption>
          </additionalOptions>
          <javadocExecutable>${java.home}/bin/javadoc</javadocExecutable>
        </configuration>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <argLine>-Duser.language=de -Duser.region=DE</argLine>
          <excludes>
            <!-- add test classes to exclude here -->
            <exclude>**/AngebotGeneratorServiceTest.java</exclude>
            <exclude>**/KasseGeneratorServiceTest.java</exclude>
            <exclude>**/GutschriftV1GeneratorServiceTest.java</exclude>
            <exclude>**/GutschriftV2GeneratorServiceTest.java</exclude>
            <exclude>**/RechnungV1GeneratorServiceTest.java</exclude>
            <exclude>**/RechnungV2GeneratorServiceTest.java</exclude>
          </excludes>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

<!--  <reporting>-->
<!--    <plugins>-->
<!--      <plugin>-->
<!--        <groupId>org.codehaus.mojo</groupId>-->
<!--        <artifactId>versions-maven-plugin</artifactId>-->
<!--        <version>${plugin.version.versions}</version>-->
<!--        <configuration>-->
<!--          <ruleSet>-->
<!--            <ignoreVersions>-->
<!--              <igonreVersion>-->
<!--                <type>regex</type>-->
<!--                <version>(.+-M\d)</version>-->
<!--              </igonreVersion>-->
<!--              <igonreVersion>-->
<!--                <type>regex</type>-->
<!--                <version>.+-(alpha|beta).+</version>-->
<!--              </igonreVersion>-->
<!--            </ignoreVersions>-->
<!--          </ruleSet>-->
<!--        </configuration>-->
<!--        <reportSets>-->
<!--          <reportSet>-->
<!--            <reports>-->
<!--              <report>dependency-updates-report</report>-->
<!--              <report>plugin-updates-report</report>-->
<!--              <report>property-updates-report</report>-->
<!--            </reports>-->
<!--          </reportSet>-->
<!--        </reportSets>-->
<!--      </plugin>-->
<!--    </plugins>-->
<!--  </reporting>-->
</project>
